language: scala

env:
  global:
  - ANDROID_HOME=$PWD/android-sdk-linux
  - ANDROID_SDK_VERSION=23.0.2
  - ANDROID_BUILD_TOOLS_VERSION=21.1.1
  - ANDROID_API_LEVEL=19
  - BINTRAY_ORG=${TRAVIS_REPO_SLUG%/*}
  - BINTRAY_PKG=${TRAVIS_REPO_SLUG#*/}
  - BINTRAY_API=https://bintray.com/api/v1
  - secure: Tf5EVE4O5NUu6tcYxS2+RUIkGMohTmMyXYCtJysjEGHieQtYYvCxW40tGKQAsqmCyo0G2ObPHQsnZoIagFVd/+MnxWeyyZuNFG2b86L/vpp58Pdz53LyUDY3BL9hbeHkJI68FQzaitzbxGmc1P8Ocsg5lFLUDOs/UsjFzFoOTFc=
  - secure: fS4wYeFopSVSda6S3RR7eE658CCf8PBnP3cq0DBUs6iUBp1gRzYvBD4sFD2L3vLiE0m88M824XYrT+m4uoUdZo3/KZ3NDNX3pDBAfLAzN5HG+N30ss6O9OBSmA6sEuHIuCjfyejmyC5DnShZsR4iKoa55b4lynAezpuAUZmuGwk=

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq lib32stdc++6 lib32z1
- wget http://dl.google.com/android/android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- tar -zxf android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- echo yes | ${ANDROID_HOME}/tools/android update sdk --filter tools,platform-tools,build-tools-${ANDROID_BUILD_TOOLS_VERSION},android-${ANDROID_API_LEVEL},extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force --no-https --all > /dev/null

script: "sbt coveralls"

