language: scala

env:
  global:
  - ANDROID_HOME=$PWD/android-sdk-linux
  - ANDROID_SDK_VERSION=23.0.2
  - ANDROID_BUILD_TOOLS_VERSION=21.1.1
  - ANDROID_API_LEVEL=19

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq lib32stdc++6 lib32z1
- wget http://dl.google.com/android/android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- tar -zxf android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- echo yes | ${ANDROID_HOME}/tools/android update sdk --filter tools,platform-tools,build-tools-${ANDROID_BUILD_TOOLS_VERSION},android-${ANDROID_API_LEVEL},extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force --no-https --all > /dev/null

script: "sbt coveralls"
